export enum ItemsPurchasedFields {
    "Item Cart Cannon",
    "Item Cart Laser",
    "Item Cart Medium",
    "Item Cart Small",
    "Item Drone Battery",
    "Item Drone Feather",
    "Item Drone Indestructible",
    "Item Drone Torque",
    "Item Drone Zero Gravity",
    "Item Duck Bucket",
    "Item Extraction Tracker",
    "Item Grenade Duct Taped",
    "Item Grenade Explosive",
    "Item Grenade Human",
    "Item Grenade Shockwave",
    "Item Grenade Stun",
    "Item Gun Handgun",
    "Item Gun Laser",
    "Item Gun Shockwave",
    "Item Gun Shotgun",
    "Item Gun Stun",
    "Item Gun Tranq",
    "Item Health Pack Large",
    "Item Health Pack Medium",
    "Item Health Pack Small",
    "Item Melee Baseball Bat",
    "Item Melee Frying Pan",
    "Item Melee Inflatable Hammer",
    "Item Melee Sledge Hammer",
    "Item Melee Stun Baton",
    "Item Melee Sword",
    "Item Mine Explosive",
    "Item Mine Shockwave",
    "Item Mine Stun",
    "Item Orb Zero Gravity",
    "Item Phase Bridge",
    "Item Power Crystal",
    "Item Rubber Duck",
    "Item Upgrade Map Player Count",
    "Item Upgrade Player Crouch Rest",
    "Item Upgrade Player Energy",
    "Item Upgrade Player Extra Jump",
    "Item Upgrade Player Grab Range",
    "Item Upgrade Player Grab Strength",
    "Item Upgrade Player Health",
    "Item Upgrade Player Sprint Speed",
    "Item Upgrade Player Tumble Launch",
    "Item Upgrade Player Tumble Wings",
    "Item Valuable Tracker"
}

type ItemsPurchased = {
        "Item Cart Cannon"?: number,
        "Item Cart Laser"?: number,
        "Item Cart Medium"?: number,
        "Item Cart Small"?: number,
        "Item Drone Battery"?: number,
        "Item Drone Feather"?: number,
        "Item Drone Indestructible"?: number,
        "Item Drone Torque"?: number,
        "Item Drone Zero Gravity"?: number,
        "Item Duck Bucket"?: number,
        "Item Extraction Tracker"?: number,
        "Item Grenade Duct Taped"?: number,
        "Item Grenade Explosive"?: number,
        "Item Grenade Human"?: number,
        "Item Grenade Shockwave"?: number,
        "Item Grenade Stun"?: number,
        "Item Gun Handgun"?: number,
        "Item Gun Laser"?: number,
        "Item Gun Shockwave"?: number,
        "Item Gun Shotgun"?: number,
        "Item Gun Stun"?: number,
        "Item Gun Tranq"?: number,
        "Item Health Pack Large"?: number,
        "Item Health Pack Medium"?: number,
        "Item Health Pack Small"?: number,
        "Item Melee Baseball Bat"?: number,
        "Item Melee Frying Pan"?: number,
        "Item Melee Inflatable Hammer"?: number,
        "Item Melee Sledge Hammer"?: number,
        "Item Melee Stun Baton"?: number,
        "Item Melee Sword"?: number,
        "Item Mine Explosive"?: number,
        "Item Mine Shockwave"?: number,
        "Item Mine Stun"?: number,
        "Item Orb Zero Gravity"?: number,
        "Item Phase Bridge"?: number,
        "Item Power Crystal"?: number,
        "Item Rubber Duck"?: number,
        "Item Upgrade Map Player Count"?: number,
        "Item Upgrade Player Crouch Rest"?: number,
        "Item Upgrade Player Energy"?: number,
        "Item Upgrade Player Extra Jump"?: number,
        "Item Upgrade Player Grab Range"?: number,
        "Item Upgrade Player Grab Strength"?: number,
        "Item Upgrade Player Health"?: number,
        "Item Upgrade Player Sprint Speed"?: number,
        "Item Upgrade Player Tumble Launch"?: number,
        "Item Upgrade Player Tumble Wings"?: number,
        "Item Valuable Tracker"?: number
    }

    export type { ItemsPurchased }